#!/bin/zsh

set -e

function usage() {
  echo "Usage:"
  echo
  echo "$0 passPhrase expiration"
  echo
  echo "Where:"
  echo "  passPhrase - The pass phrase to unlock the API keys"
  echo "  expiration - The date in yy-mm-dd form of the latest desired expiration date"
  echo
  echo "Example:"
  echo "  $0 topSecret123 2021-11-26"
  exit
}

[[ $# -ne 2 ]] && usage

passPhrase=$1
expiration=$2

# Make sure we are using the latest code
git pull --quiet

# Clean old files out of the cache; they are only good for a weekend
mkdir -p web-request-cache
find web-request-cache -type f -mmin +4320 -delete

# Clean out any old options runs
find . -name "??_*_puts.csv" -depth 1 -delete
find . -name "??_*_calls.csv" -depth 1 -delete

# Clean out expired tokens; they are only good for about a week
find . -type f -name token.json -depth 1 -mmin +12960 -delete

# Precache candles. We sometimes exceed our MarketData API request quota.
# Cache these earlier in the week so our quota can reset in time for the
# big run below.
caffeinate -i go run precache/main.go -passPhrase "${passPhrase}"

echo

# Dont generate the spreadsheets if the market has not closed for the week.
WEEKDAY=$( date "+%u" )
HOUR=$( date "+%H" )
[[ ${WEEKDAY} -lt 5 ]] && echo "Too early: day ${WEEKDAY}" && exit
[[ ${WEEKDAY} -eq 5 ]] && [[ ${HOUR} -lt 16 ]] && echo "Too early: day ${WEEKDAY} hour ${HOUR}" && exit

# This can be a long run. Don't let the Mac sleep during it.
caffeinate -i go run main/main.go -passPhrase "${passPhrase}" -expiration "${expiration}"
