#!/bin/zsh

set -e

function usage() {
  echo "Usage:"
  echo
  echo "$0 passPhrase expiration"
  echo
  echo "Where:"
  echo "  passPhrase - The pass phrase to unlock the API keys"
  echo "  expiration - The date in yymmdd form of the latest possible expiration date"
  echo
  echo "Example:"
  echo "  $0 topSecret123 20211126"
  exit
}

# If there is a USE_* file, regenerate the list of interesting options (options.csv).
function regenerate() {
  mv ~/Downloads/USE_* . || true
  exists=$( find . -name "USE_*" | wc -l )
  [[ ${exists} -eq 0 ]] && return
  go run main.go -passPhrase ${passPhrase} -regenerate -useFile USE_*
  mv USE_*.options.csv options.csv
  git --no-pager diff --unified=0 --color=always options.csv | egrep -v "@@"
}

[[ $# -ne 2 ]] && usage

passPhrase=$1
expiration=$2

# Make sure we are using the latest code.
git pull

# Clean old files out of the cache. They are only good for a day.
mkdir -p web-request-cache
find web-request-cache -type f -mmin +1440 -delete

# Clean out any old options runs
find . -name "options_??_*.csv" -depth 1 -delete

# Clean out expired tokens. They are only good for around a week.
find . -type f -name token.json -depth 1 -mmin +12960 -delete

# Make sure all the code is clean/healthy/working.
go fmt ./...
go vet ./...
go test ./...

regenerate

go run main.go -passPhrase ${passPhrase} -expiration ${expiration}
